### ISSUE TITLE
NPE when loaders are not specified for Modrinth

### ISSUE THREAD

**Issue by Crystal-Spider** [firstdarkdev/modpublisher#22]
If I don't set any loaders or I set them to an empty list, Modrinth publish will fail:
```
Caused by: java.lang.NullPointerException: loaders is marked non-null but is null
	at masecla.modrinth4j.endpoints.version.CreateVersion$CreateVersionRequest.<init>(CreateVersion.java:42)
	at masecla.modrinth4j.endpoints.version.CreateVersion$CreateVersionRequest$CreateVersionRequestBuilder.build(CreateVersion.java:41)
	at com.hypherionmc.modpublisher.tasks.ModrinthPublishTask.upload(ModrinthPublishTask.java:159)
```

I think this could be fixed easily just by removing the empty check [here](https://github.com/firstdarkdev/modpublisher/blob/cee8eac9fee36809434454ecb193016f62dd1cee/src/main/java/com/hypherionmc/modpublisher/tasks/ModrinthPublishTask.java#L111).

My use case is the following:  
I have a multiloader project setup, and I want to configure publishing tasks for each loader submodule, so I do that in the root build.gradle. This configures the tasks for the common submodule too, which is correct as it allows me to call the tasks from the root module instead of having to call them for each submodule.  
However, when the tasks run for common, I don't have a specific loader to set. Anyway, everything is run in debug mode for common.  
It seems a bit weird to forcefully set a random loader in common just to avoid Modrinth from failing, considering it doesn't seem to be a problem for CurseForge, so I'd like to be able to not set the loaders and the task to still run successfully.

**Comment by hypherionmc** [comment]
The "NPE on no loaders" is intentional. Modrinth does not allow uploading files, that don't have loaders added to them, so the error you are seeing, is from modrinth themselves and not from us. Even if you pass an empty loaders list to their api, it will still fail. It needs at least one valid loader

We talked to them in the past about removing this requirement, but they refuse to do so.

a workaround for you may be to add `publishModrinth.enabled = false` in your common project. That should stop it from trying to upload

**Comment by Crystal-Spider** [comment]
Oh okay, I'll try like that and, if it doesn't work, I'll go back to my other workaround.  
Thanks!
